In [1]:
conda install numpy


Note: you may need to restart the kernel to use updated packages.



CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/main/win-64/current_repodata.json (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000005E59C48>, 'Connection to repo.anaconda.com timed out. (connect timeout=9.15)'))"))




In [1]:
import numpy as np

In [2]:
mylist = [1,2,3,4,5]

In [3]:
arr = np.array(mylist)

In [4]:
type(arr)

numpy.ndarray

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr.shape

(5,)

In [7]:
arr

array([1, 2, 3, 4, 5])

arr is a one-dimensional array and hence arr.shape returns (5,)

In [8]:
mylist1 = [1,2,3,4,5]
mylist2 = [1,2,3,4,5]
mylist3 = [1,2,3,4,5]

In [10]:
arr = np.array([mylist1, mylist2, mylist3])

In [11]:
arr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [12]:
arr.shape

(3, 5)

In [13]:
type(arr)

numpy.ndarray

In [14]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 1],
       [2, 3, 4],
       [5, 1, 2],
       [3, 4, 5]])

In [15]:
arr.shape

(3, 5)

Converting any data to arrays makes the process fast.

Reshaping needs the number of total elements from source and target must be equal

In [16]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]])

In [17]:
arr.shape

(3, 5)

# Indexing

In [18]:
# Accessing the array element

arr = np.array([1,2,3,4,5,6,7,8,9])

In [19]:
arr[3]

4

In [20]:
mylist1 = [1,2,3,4,5]
mylist2 = [6,7,8,9,10]
mylist3 = [11,12,13,14,15]

arr = np.array([mylist1, mylist2, mylist3])

In [21]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [22]:
arr[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [24]:
arr[2,4]

15

In [25]:
arr[0:2,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [26]:
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [27]:
arr[1:,3:]

array([[ 9, 10],
       [14, 15]])

In [28]:
arr[1,1:4]

array([7, 8, 9])

In [29]:
arr[1:,2:4]

array([[ 8,  9],
       [13, 14]])

In [30]:
arr = np.arange(0,10)

In [2]:
arr

NameError: name 'arr' is not defined

In [32]:
arr = np.arange(0,10, step=2)

In [33]:
arr

array([0, 2, 4, 6, 8])

In [34]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [35]:
np.linspace(1,10, 100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

Divides the start and end (1 and 10 in this case) into mentioned number of equal parts (100 in the above example)

In [37]:
# Copy() function and broadcasting

arr1 = arr

In [38]:
arr1

array([0, 2, 4, 6, 8])

In [39]:
arr1[3:] = 100

In [40]:
arr1

array([  0,   2,   4, 100, 100])

In [41]:
print(arr)

[  0   2   4 100 100]


Changing the copied array will result in the original array getting updated, this is because this works by copy of reference rather than value. 

To avoid this, we use copy() function

In [42]:
arr2 = arr.copy()

In [43]:
arr

array([  0,   2,   4, 100, 100])

In [44]:
arr2

array([  0,   2,   4, 100, 100])

In [45]:
arr2[3:] = 500

In [46]:
arr2

array([  0,   2,   4, 500, 500])

In [47]:
arr

array([  0,   2,   4, 100, 100])

In [6]:
# Some very useful conditions in exploratory analysis

import numpy as np

val = 2
mylist = [1,2,3,4,5,6,7]

arr = np.array(mylist)
arr < 2

# The above statement will check each element in array against '2'. Similarly all other operators apply.

array([ True, False, False, False, False, False, False])

In [7]:
arr * 2

array([ 2,  4,  6,  8, 10, 12, 14])

In [9]:
# We can retrieve elements based on a condition

arr[arr<5]

array([1, 2, 3, 4])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,100, step=20)

array([ 0, 20, 40, 60, 80])

In [12]:
arr2 = np.array([2,4,6,8,10])

In [13]:
arr*arr2

ValueError: operands could not be broadcast together with shapes (7,) (5,) 

In [14]:
arr3 = np.array([1,-1,1,-1,1,-1,1])

In [16]:
arr.shape

(7,)

In [18]:
arr3.shape

(7,)

In [19]:
arr * arr3

array([ 1, -2,  3, -4,  5, -6,  7])

In [20]:
# np.ones(n) creates an array of mentioned size 'n' where all elements are '1'

np.ones(5)

array([1., 1., 1., 1., 1.])

here we see 1. because the default datatype is float, we can override it as below.

In [21]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [22]:
# We can create 2-D arrays using this as below

np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
# Random Distribution

np.random.rand(3,3)

array([[0.62927567, 0.53336473, 0.14215854],
       [0.04810893, 0.29045849, 0.49875157],
       [0.0206694 , 0.16545844, 0.2668594 ]])

In [24]:
np.random

<module 'numpy.random' from 'C:\\Users\\s2882679\\Anaconda\\lib\\site-packages\\numpy\\random\\__init__.py'>

In [27]:
# There is another method called 'randn' which creates an array of random elements using "Standard Normal" distribution

std_arr = np.random.randn(3,3)
std_arr

array([[ 1.48512663,  0.13352876,  0.70192547],
       [-0.74581201,  0.51252331, -0.91899524],
       [-1.64807161,  0.38800985,  0.37519173]])

In [28]:
import seaborn as sb
import pandas as pd

sb.distplot(pd.DataFrame(std_arr.reshape(9,1)))

C:\Users\s2882679\Anaconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\s2882679\Anaconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\s2882679\Anaconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [29]:
np.random.randint(0,100,8).reshape(4,2)

array([[33, 97],
       [ 5, 31],
       [94, 57],
       [83, 53]])

In [30]:
# random_sample(size=None)
# Return random floats in the half-open interval [0.0, 1.0).

np.random.random_sample((1,5))

array([[0.38239958, 0.72690125, 0.61238912, 0.41934296, 0.50684626]])